WebBooking/Controllers/TaiKhoanController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using WebBooking.Models;

namespace WebBooking.Controllers
{
    [Authorize]
    public class TaiKhoanController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public TaiKhoanController()
        {
        }

        public TaiKhoanController(ApplicationUserManager userManager, ApplicationSignInManager signInManager )
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            var result = await SignInManager.PasswordSignInAsync(model.UserName, model.Password, model.RememberMe, shouldLockout: false);

            if (result == SignInStatus.Success)
            {
                var user = await UserManager.FindAsync(model.UserName, model.Password);

                if (await UserManager.IsInRoleAsync(user.Id, "Admin"))
                {
                    return RedirectToAction("Index", "Home", new { area = "Admin" });
                }
                else if (await UserManager.IsInRoleAsync(user.Id, "NhanVien"))
                {
                    return RedirectToAction("Index", "Home", new { area = "Admin" });
                }
                else if (await UserManager.IsInRoleAsync(user.Id, "KhachHang"))
                {
                    return RedirectToAction("TrangChu", "TrangChu");
                }
                else
                {
                    return RedirectToAction("TrangChu", "TrangChu");
                }
            }

            switch (result)
            {
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        //
        // GET: /Account/VerifyCode
        [AllowAnonymous]
        public async Task<ActionResult> VerifyCode(string provider, string returnUrl, bool rememberMe)
        {
            // Require that the user has already logged in via username/password or external login
            if (!await SignInManager.HasBeenVerifiedAsync())
            {
                return View("Error");
            }
            return View(new VerifyCodeViewModel { Provider = provider, ReturnUrl = returnUrl, RememberMe = rememberMe });
        }

        //
        // POST: /Account/VerifyCode
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyCode(VerifyCodeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // The following code protects for brute force attacks against the two factor codes. 
            // If a user enters incorrect codes for a specified amount of time then the user account 
            // will be locked out for a specified amount of time. 
            // You can configure the account lockout settings in IdentityConfig
            var result = await SignInManager.TwoFactorSignInAsync(model.Provider, model.Code, isPersistent:  model.RememberMe, rememberBrowser: model.RememberBrowser);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(model.ReturnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid code.");
                    return View(model);
            }
        }

        //
        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { 
                    UserName = model.UserName,
                    Email = model.Email, 
                    PhoneNumber = model.PhoneNumber,
                    Birthday = model.Birthday,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Avatar = model.Avatar
                };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent:false, rememberBrowser:false);
                    
                    // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ConfirmEmail
        [AllowAnonymous]
        public async Task<ActionResult> ConfirmEmail(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return View("Error");
            }
            var result = await UserManager.ConfirmEmailAsync(userId, code);
            return View(result.Succeeded ? "ConfirmEmail" : "Error");
        }

        //
        // GET: /Account/ForgotPassword
        [AllowAnonymous]
        public ActionResult ForgotPassword()
        {
            return View();
        }

        //
        // POST: /Account/ForgotPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByNameAsync(model.Email);
                if (user == null || !(await UserManager.IsEmailConfirmedAsync(user.Id)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return View("ForgotPasswordConfirmation");
                }

                // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                // Send an email with this link
                // string code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
                // var callbackUrl = Url.Action("ResetPassword", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);		
                // await UserManager.SendEmailAsync(user.Id, "Reset Password", "Please reset your password by clicking <a href=\"" + callbackUrl + "\">here</a>");
                // return RedirectToAction("ForgotPasswordConfirmation", "Account");
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ForgotPasswordConfirmation
        [AllowAnonymous]
        public ActionResult ForgotPasswordConfirmation()
        {
            return View();
        }

        //
        // GET: /Account/ResetPassword
        [AllowAnonymous]
        public ActionResult ResetPassword(string code)
        {
            return code == null ? View("Error") : View();
        }

        //
        // POST: /Account/ResetPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]

WebBooking/Views/TaiKhoan/ConfirmEmail.cshtml
@{
    ViewBag.Title = "Confirm Email";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <div>
        <p>
            Thank you for confirming your email. Please @Html.ActionLink("Click here to Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
        </p>
    </div>
</main>

WebBooking/Views/TaiKhoan/ExternalLoginConfirmation.cshtml
@model WebBooking.Models.ExternalLoginConfirmationViewModel
@{
    ViewBag.Title = "Register";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>Associate your @ViewBag.LoginProvider account.</h3>

    @using (Html.BeginForm("ExternalLoginConfirmation", "TaiKhoan", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form" }))
    {
        @Html.AntiForgeryToken()

        <h4>Association Form</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <p class="text-info">
            You've successfully authenticated with <strong>@ViewBag.LoginProvider</strong>.
            Please enter a user name for this site below and click the Register button to finish
            logging in.
        </p>
        <div class="row">
            @Html.LabelFor(m => m.Email, new { @class = "col-md-2 col-form-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="offset-md-2 col-md-10">
                <input type="submit" class="btn btn-outline-dark" value="Register" />
            </div>
        </div>
    }
</main>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebBooking/Views/TaiKhoan/ExternalLoginFailure.cshtml
@{
    ViewBag.Title = "Login Failure";
}

<main>
    <hgroup>
        <h2>@ViewBag.Title.</h2>
        <h3 class="text-danger">Unsuccessful login with service.</h3>
    </hgroup>
</main>

WebBooking/Views/TaiKhoan/LogOff.cshtml
@{
    ViewBag.Title = "LogOff";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>LogOff</h2>

WebBooking/Views/TaiKhoan/Login.cshtml
@using WebBooking.Models
@model LoginViewModel
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Spica Admin</title>
    <!-- base:css -->
    <link href="~/Content/asetsaccount/vendors/mdi/css/materialdesignicons.min.css" rel="stylesheet" />
    <link href="~/Content/asetsaccount/vendors/css/vendor.bundle.base.css" rel="stylesheet" />

    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link href="~/Content/asetsaccount/css/style.css" rel="stylesheet" />
    <!-- endinject -->
    <link rel="shortcut icon" href="../../images/favicon.png" />
</head>

<body>
    <div class="container-scroller d-flex">
        <div class="container-fluid page-body-wrapper full-page-wrapper d-flex">
            <div class="content-wrapper d-flex align-items-stretch auth auth-img-bg">
                <div class="row flex-grow">
                    <div class="col-lg-6 d-flex align-items-center justify-content-center">
                        <div class="auth-form-transparent text-left p-3">
                            <div class="brand-logo">
                                <a href="@Url.Action("TrangChu","TrangChu",new { })"><img style="width:1200px" src="~/Content/assets/images/Logo/logo.jpg" alt="logo"></a>
                            </div>
                            <h1 style="color: burlywood; margin-left: 200px; font-family: Courier New Courier ">Đăng Nhập</h1>
                            <form class="pt-3">
                            </form>
                            @using (Html.BeginForm("Login", "TaiKhoan", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form" }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="form-group">
                                    <label style="font-size:20px" for="exampleInputEmail">Tài Khoản</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="mdi mdi-account-outline text-primary"></i>
                                            </span>
                                        </div>
                                        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label style="font-size:20px" for="exampleInputEmail">Mật Khẩu</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="mdi mdi-lock-outline text-primary"></i>
                                            </span>
                                        </div>
                                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div my-2 d-flex justify-content-between align-items-center">
                                    <div class="offset-md-1 col-md-10">
                                        <div class="checkbox">
                                            @Html.CheckBoxFor(m => m.RememberMe)
                                            @Html.LabelFor(m => m.RememberMe)
                                        </div>
                                    </div>
                                </div>
                                <div class="my-3">
                                    <input style="margin-left:190px" type="submit" value="Đăng Nhập" class="btn btn-outline-dark" />
                                </div>
                                <div class="mb-2 d-flex">
                                    <button type="button" class="btn btn-facebook auth-form-btn flex-grow me-1">
                                        <i class="mdi mdi-facebook me-2"></i>Facebook
                                    </button>
                                    <button type="button" class="btn btn-google auth-form-btn flex-grow ml-1">
                                        <i class="mdi mdi-google me-2"></i>Google
                                    </button>
                                </div>
                                @*<div class="col-md-4">
                                    <section id="socialLoginForm">
                                        @Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
                                    </section>
                                </div>*@
                                <div class="text-center mt-4 font-weight-light">
                                    Bạn Đã Có Tài Khoản Chưa? || <a href="@Url.Action("Register")">Tạo Tài Khoản</a>
                                </div>
                            }
                        </div>
                    </div>
                    <div class="col-lg-6 login-half-bg d-none d-lg-flex flex-row">
                        <p class="text-white font-weight-medium text-center flex-grow align-self-end"></p>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- base:js -->
    <script src="~/Content/asetsaccount/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <script src="~/Content/asetsaccount/js/jquery.cookie.js" type="text/javascript"></script>
    <!-- inject:js -->
    <script src="~/Content/asetsaccount/js/off-canvas.js"></script>
    <script src="~/Content/asetsaccount/js/hoverable-collapse.js"></script>
    <script src="~/Content/asetsaccount/js/template.js"></script>
    <!-- endinject -->
</body>

</html>

WebBooking/Views/TaiKhoan/Register.cshtml
@model WebBooking.Models.RegisterViewModel
@{
    ViewBag.Title = "Register";
}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Spica Admin</title>
    <!-- base:css -->
    <link href="~/Content/asetsaccount/vendors/mdi/css/materialdesignicons.min.css" rel="stylesheet" />
    <link href="~/Content/asetsaccount/vendors/css/vendor.bundle.base.css" rel="stylesheet" />

    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link href="~/Content/asetsaccount/css/style.css" rel="stylesheet" />
    <!-- endinject -->
    <link rel="shortcut icon" href="../../images/favicon.png" />
</head>

<body>
    <div class="container-scroller d-flex">
        <div class="container-fluid page-body-wrapper full-page-wrapper d-flex">
            <div class="content-wrapper d-flex align-items-stretch auth auth-img-bg">
                <div class="row flex-grow">
                    <div class="col-lg-6 d-flex align-items-center justify-content-center">
                        <div class="auth-form-transparent text-left p-3">
                            <div class="brand-logo">
                                <a href="@Url.Action("TrangChu","TrangChu",new { })"><img style="width:1200px" src="~/Content/assets/images/Logo/logo.jpg" alt="logo"></a>
                            </div>
                            <h1 style="color: burlywood; margin-left: 200px; font-family: Courier New Courier ">Đăng Ký</h1>
                            <form class="pt-3">
                            </form>
                            @using (Html.BeginForm("Register", "TaiKhoan", FormMethod.Post, new { role = "form" }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="form-group">
                                    <label style="font-size:20px" for="exampleInputAccount">Tài Khoản</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="mdi mdi-account-outline text-primary"></i>
                                            </span>
                                        </div>
                                        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label style="font-size:20px" for="exampleInputEmail">Gmail</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="mdi mdi-email-outline text-primary"></i>
                                            </span>
                                        </div>
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label style="font-size:20px" for="exampleInputNumber">Số Điện Thoại</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="fa fa-phone text-primary"></i>
                                            </span>
                                        </div>
                                        @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })

                                    </div>
                                </div>
                                <div class="form-group">
                                    <label style="font-size:20px" for="exampleInputFirstName">Họ</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="mdi mdi-account-outline text-primary"></i>
                                            </span>
                                        </div>
                                        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label style="font-size:20px" for="exampleInputLastName">Họ</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="mdi mdi-account-outline text-primary"></i>
                                            </span>
                                        </div>
                                        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label style="font-size:20px" for="exampleInputBirthday">Sinh nhật</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="fa fa-phone text-primary"></i>
                                            </span>
                                        </div>
                                        @Html.TextBoxFor(m => m.Birthday, new { @class = "form-control", @id = "Birthday", @type = "date" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label style="font-size:20px" for="exampleInputBirthday">Ảnh đại diện</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="fa fa-image text-primary"></i>
                                            </span>
                                        </div>
                                        @Html.TextBoxFor(m => m.Avatar, new { @class = "form-control" })
                                        <a href="#" class="btn btn-success btn-sm" onclick="BrowseServer()">Chọn hình ảnh</a>
                                        @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label style="font-size:20px" for="exampleInputPassword">Mật Khẩu</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="mdi mdi-lock-outline text-primary"></i>
                                            </span>
                                        </div>
                                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label style="font-size:20px" for="exampleInputEmail">Nhập Lại Mật Khẩu</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend bg-transparent">
                                            <span class="input-group-text bg-transparent border-right-0">
                                                <i class="mdi mdi-lock-outline text-primary"></i>
                                            </span>
                                        </div>
                                        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="my-3">
                                    <input style="margin-left:190px" type="submit" value="Đăng Ký" class="btn btn-outline-dark" />
                                </div>
                                <div class="mb-2 d-flex">
                                    <button type="button" class="btn btn-facebook auth-form-btn flex-grow me-1">
                                        <i class="mdi mdi-facebook me-2"></i>Facebook
                                    </button>
                                    <button type="button" class="btn btn-google auth-form-btn flex-grow ml-1">
                                        <i class="mdi mdi-google me-2"></i>Google
                                    </button>
                                </div>
                                <div class="text-center mt-4 font-weight-light">
                                    Bạn Đã Có Tài Khoản Rồi <a href="@Url.Action("Login")">   Đăng Nhập</a>
                                </div>
                            }
                        </div>
                    </div>
                    <div class="col-lg-6 login-half-bg d-none d-lg-flex flex-row">
                        <p class="text-white font-weight-medium text-center flex-grow align-self-end"></p>
                    </div>
                </div>
            </div>
            <!-- content-wrapper ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- base:js -->
    <script src="~/Content/asetsaccount/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <script src="~/Content/asetsaccount/js/jquery.cookie.js" type="text/javascript"></script>
    <!-- inject:js -->
    <script src="~/Content/asetsaccount/js/off-canvas.js"></script>
    <script src="~/Content/asetsaccount/js/hoverable-collapse.js"></script>
    <script src="~/Content/asetsaccount/js/template.js"></script>
    <!-- endinject -->
</body>

</html>
@section ckfinder{
    <script>
        CKEDITOR.replace('inputdes')
        //hình ảnh
        function BrowseServer() {
            var finder = new CKFinder();
            finder.selectActionFunction = SetFileField;
            finder.popup();
        }
        function SetFileField(fileUrl) {
            document.getElementById('Avatar').value = fileUrl;
        }
    </script>
}