WebBooking/Controllers/LoaiPhongController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Metadata.Edm;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBooking.Models.DB;

namespace WebBooking.Controllers
{
    public class LoaiPhongController : Controller
    {
        dbHotel db = new dbHotel();
        // GET: /Category
        public ActionResult CacLoaiPhong()
        {
            // Lấy danh sách các mã loại phòng
            List<Category> categories = db.Categories.ToList();

            return View(categories);
        }
        public ActionResult Phong(int id)
        {
            // Lấy mã loại phòng
            Category categories = db.Categories.Find(id);

            if (categories == null)
            {
                return HttpNotFound();
            }

            // Lấy danh sách các phòng thuộc loại này
            List<Room> rooms = db.Rooms.Where(r => r.categoryid == id).ToList();

            ViewBag.categoryroom = categories.categoryname;

            return View(rooms);
        }
        public ActionResult ChiTietPhong(int id)
        {
            var category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }

            return View(category);
        }
    }
}

WebBooking/Controllers/PhongController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBooking.Models.DB;

namespace WebBooking.Controllers
{
    public class PhongController : Controller
    {
        dbHotel db = new dbHotel();
        // GET: TinTuc
        public ActionResult CacPhong(int? page, string searchTerm)
        {

            List<Category> categories = db.Categories.ToList();
            ViewBag.Categories = categories;

            int pageSize = 6;
            int pageNum = page ?? 1;

            // Lấy danh sách phòng từ nguồn dữ liệu và truyền nó tới view
            List<Room> roomList = GetRoomsFromDataSource();
            if (searchTerm != null)
            {
                var room = db.Rooms
                .Where(r => r.roomname.Contains(searchTerm))
                .ToList();
                return View(room.ToPagedList(pageNum, pageSize));
            }
            return View(roomList.ToPagedList(pageNum, pageSize));
        }
        private List<Room> GetRoomsFromDataSource()
        {
            // Thực hiện truy vấn hoặc logic để lấy danh sách tin tức từ nguồn dữ liệu
            // Ví dụ: sử dụng Entity Framework để truy vấn từ bảng News

            using (var context = new dbHotel())
            {
                List<Room> roomList = context.Rooms.ToList();
                return roomList;
            }
        }
        public ActionResult ChiTietPhong(int id)
        {
            var room = db.Rooms.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }

            return View(room);
        }
        // Action tìm kiếm phòng
        public ActionResult TimKiem(string searchTerm)
        {
            var rooms = db.Rooms
                .Where(r => r.roomname.Contains(searchTerm) || r.Category.categoryname.Contains(searchTerm))
                .ToList();
            return View(rooms);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WebBooking/Views/LoaiPhong/CacLoaiPhong.cshtml
@model IEnumerable<WebBooking.Models.DB.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="gdlr-header-substitute">
</div>
<div class="gdlr-page-title-wrapper">
    <div class="gdlr-page-title-overlay"></div>
    <div class="gdlr-page-title-container container">
        <h1 class="gdlr-page-title">Các Loại Phòng</h1>
        <span class="gdlr-page-caption">Trang Các Loại Phòng</span>
    </div>
</div>
<!-- is search -->
<div class="content-wrapper">
    <div class="gdlr-content">
        <!-- Above Sidebar Section-->
        <!-- Sidebar With Content Section-->
        <div class="with-sidebar-wrapper">
            <section id="content-section-1">
                <div class="section-container container">
                    <div class="room-item-wrapper type-classic" style="margin-bottom: 30px;">
                        <div class="room-item-holder ">
                            <div class="clear"></div>
                            @foreach (var item in Model)
                            {
                                <div class="four columns">
                                    <div class="gdlr-item gdlr-room-item gdlr-classic-room">
                                        <div class="gdlr-ux gdlr-classic-room-ux">
                                            <div class="gdlr-room-thumbnail">
                                                @*<a href="#"><img src="~/Content/assets/images/hotels/StandardTwinRoomWithSofa/room1.jpg" alt="" width="700" height="400"></a>*@
                                                <a href="@Url.Action("Phong", "LoaiPhong", new { @id = item.categoryid },null)"><img style="width:700px; height:300px" src="@item.image" alt=""></a>
                                            </div>
                                            <h3 class="gdlr-room-title"><a href="@Url.Action("Phong", "LoaiPhong", new { @id = item.categoryid },null)">@item.categoryname</a></h3>
                                            <div class="gdlr-hotel-room-info">
                                                <div class="clear"></div>
                                            </div><a class="gdlr-button with-border" href="@Url.Action("Phong", "LoaiPhong", new { @id = item.categoryid },null)">Xem Các Phòng<i class="fa fa-long-arrow-right icon-long-arrow-right"></i></a>
                                        </div>
                                    </div>
                                </div>
                            }
                            <div class="clear"></div>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </section>
        </div>
        <!-- Below Sidebar Section-->
    </div>
    <!-- gdlr-content -->
    <div class="clear"></div>
</div>

WebBooking/Views/LoaiPhong/Details.cshtml
@model WebBooking.Models.DB.Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.categoryname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categorydes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categorydes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.categoryid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebBooking/Views/LoaiPhong/Phong.cshtml
@model IEnumerable<WebBooking.Models.DB.Room>

@{
    ViewBag.Title = "Room";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="gdlr-header-substitute">
</div>
<div class="gdlr-page-title-wrapper">
    <div class="gdlr-page-title-overlay"></div>
    <div class="gdlr-page-title-container container">
        <h1 class="gdlr-page-title">Các Phòng</h1>
        <span class="gdlr-page-caption">Quý khách hãy chọn cho mình một căn phòng ưng ý</span>
    </div>
</div>
<!-- is search -->
<div class="content-wrapper">
    <div class="gdlr-content">
        <!-- Above Sidebar Section-->
        <!-- Sidebar With Content Section-->
        <div class="with-sidebar-wrapper">
            <section id="content-section-1">
                <div class="section-container container">
                    <div class="room-item-wrapper type-classic" style="margin-bottom: 30px;">
                        <div class="room-item-holder ">
                            <div class="clear"></div>
                            @foreach (var item in Model)
                            {
                                <div class="four columns">
                                    <div class="gdlr-item gdlr-room-item gdlr-classic-room">
                                        <div class="gdlr-ux gdlr-classic-room-ux">
                                            <div class="gdlr-room-thumbnail">
                                                <a href="@Url.Action("ChiTietPhong", "Phong", new { @id = item.roomid },null)"><img style="width:700px; height:300px" src="@item.image" alt=""></a>
                                            </div>
                                            <h3 style="font-size:30px" class="gdlr-room-title"><a href="@Url.Action("ChiTietPhong", "Phong", new { @id = item.roomid },null)">@item.roomname</a></h3>
                                            <div style="color:white" class="gdlr-hotel-room-info">
                                                <div style="font-size: 18px" class="gdlr-room-info"><i class="fa fa-check-square-o icon-check"></i><span class="gdlr-head">Bed</span><span class="gdlr-tail">@item.bed</span></div>
                                                <div style="font-size: 18px" class="gdlr-room-info"><i class="fa fa-check-square-o icon-check"></i><span class="gdlr-head">Max People</span><span class="gdlr-tail">@item.maxpeople</span></div>
                                                <div style="font-size: 18px" class="gdlr-room-info"><i class="fa fa-check-square-o icon-check"></i><span class="gdlr-head">View</span><span class="gdlr-tail">@item.view</span></div>
                                                <div style="font-size: 18px" class="gdlr-room-info"><i class="fa fa-check-square-o icon-check"></i><span class="gdlr-head">Wifi</span><span class="gdlr-tail">Có</span></div>
                                                <div style="font-size: 25px; color: #b89f80" class="gdlr-room-category-item"><i class="fa fa-dollar"></i><span class="gdlr-head">Giá: </span><span class="gdlr-tail">@String.Format("{0:0,0}", item.price) VND/Đêm</span></div>
                                                <div class="clear"></div>
                                            </div><a class="gdlr-button with-border" href="@Url.Action("ChiTietPhong", "Phong", new { @id = item.roomid },null)">Chi Tiết Phòng<i class="fa fa-long-arrow-right icon-long-arrow-right"></i></a>
                                            <a class="gdlr-button with-border" href="@Url.Action("DatPhong", "DatPhong", new { @id = item.roomid },null)">Đặt Phòng<i class="fa fa-long-arrow-right icon-long-arrow-right"></i></a>
                                        </div>
                                    </div>
                                </div>
                            }
                            <div class="clear"></div>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </section>
        </div>
        <!-- Below Sidebar Section-->
    </div>
    <!-- gdlr-content -->
    <div class="clear"></div>
</div>